name: "Explyt Chat bug"
description: "Any problem in Explyt Test plugin related to Explyt Chat"
title: ""
labels: test-chat-bug
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting Explyt Test plugin bug!"

  - type: textarea
    id: details
    attributes:
      label: Problem details
      description: "Describe the problem you faced"
      placeholder: |
        Example:
        - Class was not added to Explyt Chat attachments
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "Please provide us as more details on how to reproduce this issue, as you can"
      placeholder: |
        If your project is open-sourced, show the name of your target (class, method, test class), please, and a link on GitHub.
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: "Additional information"
      description: "Any additional information that can help us to investigate the reported problem"
      placeholder: "Logs, screenshots, etc."
    validations:
      required: false

  - type: textarea
    id: plugin_version
    attributes:
      label: Plugin version
      description: "Type plugin version here"
      placeholder: "Example: 1.2.0"
    validations:
      required: false

  - type: dropdown
    id: action
    attributes:
      label: Explyt Chat interaction
      description: "Choose the action that caused the bug"
      options:
        - Add to Chat Attachments
        - Explain Code
        - Analyze for Bugs
        - Send custom text request
        - Another
      default: 0
    validations:
      required: false

  - type: dropdown
    id: llm_provider
    attributes:
      label: LLM provider
      description: "Choose LLM provider"
      options:
        - Explyt
        - Open AI
        - DeepSeek
        - Ollama
        - Another
      default: 0
    validations:
      required: true

  - type: textarea
    id: llm_model
    attributes:
      label: LLM model
      description: "Type LLM model here"
      placeholder: "Default"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: 'Example: context size, source language, etc.'
      placeholder: "Any other information that can help us"
    validations:
      required: false
