name: "Explyt Agent bug"
description: "Any problem in Explyt plugin related to agentic chat"
title: "[BUG] "
labels: bug
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting Explyt plugin bug!"
  - type: textarea
    id: details
    attributes:
      label: Problem details
      description: "Describe the problem you faced"
      placeholder: |
        Example:
        - Edit tool failed several times with the same error
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: "Please provide us as more details on how to reproduce this issue, as you can"
      placeholder: |
        Include information about your prompt. If your project is open-sourced, show the name of your target (class, method, test class), please, and a link on GitHub.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Additional information"
      description: "Any additional information that can help us to investigate the reported problem"
      placeholder: "Prompt, logs, screenshots, etc."
    validations:
      required: false
  - type: textarea
    id: plugin_version
    attributes:
      label: Plugin version
      description: "Type plugin version here"
      placeholder: "Example: 3.0-IJ-243"
    validations:
      required: false
  - type: dropdown
    id: llm_provider
    attributes:
      label: LLM provider
      description: "Choose LLM provider"
      options:
        - Explyt Enterprise
        - Explyt
        - Open AI
        - DeepSeek
        - Ollama
        - Another
      default: 0
    validations:
      required: true
  - type: textarea
    id: llm_model
    attributes:
      label: LLM model
      description: "Type LLM model here"
      placeholder: "Default"
    validations:
      required: false
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: 'Example: context size, source language, etc.'
      placeholder: "Any other information that can help us"
    validations:
      required: false
